name: Build a release using Maven

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - run: git config --global user.name skusam
      - run: git branch release
	  - run: git checkout release
	  
      - name: Build release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          release-branch-name: "release"
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true -Dusername=skusam -Dpassword=d6c9a6452af5f6aac7ad21b08379ef91685fb768"
          maven-servers: '[{"id": "github", "username": "skusam", "password": "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"}]'

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}